@endpoint = http://localhost:8080/FAPServer/service/fapservice/
@session = e0dd9a2e-5b55-472d-ac76-48ac37229cd8

POST {{endpoint}}addUser
Accept: application/json
Content-Type: application/json

{
    "loginName": "peterl",
    "passwort": {
        "passwort": "geheim"
    },
    "vorname": "Peter",
    "nachname": "Lustig",
    "strasse": "Akazienweg 13",
    "plz": "46397",
    "ort": "Bocholt",
    "land": "Deutschland",
    "telefon": "02871/4711007",
    "email": {
        "adresse": "peterl@test.de"
    }
}
###
GET {{endpoint}}checkLoginName?id=pet
Accept: application/json
###
POST {{endpoint}}login
Accept: application/json
Content-Type: application/json

{
    "loginName": "tester",
    "passwort":
    {
        "passwort": "tester"
    }
}
###
POST {{endpoint}}logout
Accept: application/json
Content-Type: application/json

{
    "loginName": "tester",
    "sitzung": "{{session}}"
}
###
PUT {{endpoint}}setStandort
Accept: application/json
Content-Type: application/json

{
    "loginName": "tester",
    "sitzung": "{{session}}",
    "standort": {
        "breitengrad": 11,
        "laengengrad": 10
    }
}
###
GET {{endpoint}}getStandort?login=tester&session={{session}}&id=tester
Accept: application/json
###
GET {{endpoint}}getBenutzer?login=tester&session={{session}}
Accept: application/json
###
GET {{endpoint}}getStandortPerAdresse?land=Deutschland&plz=46397&ort=Bocholt&strasse=Münsterstrasse 265
Accept: application/json
